import Link from "next/link";
import { DEMO_COMPANIES, DemoBrand, CitationRiskLevel } from "@/lib/company-demo-data";
import { tx, Lang } from "@/lib/i18n";

// 4-week GEO score history (most recent last)
const BRAND_TRENDS: Record<string, number[]> = {
  "MagDrive Pro":  [18, 20, 21, 22, 24],   // slow recovery
  "JumpStart Pro": [52, 56, 60, 65, 68],   // playbook working
  "DriveSafe Pro": [38, 33, 27, 22, 18],   // declining — urgent
  "FlexWear Pro":  [30, 34, 38, 43, 47],
  "VoltEdge":      [45, 42, 38, 35, 31],
};

function GeoTrendLine({ scores }: { scores: number[] }) {
  const W = 80, H = 28;
  const min = Math.min(...scores) - 3;
  const max = Math.max(...scores) + 3;
  const range = max - min || 1;
  const pts = scores
    .map((v, i) => {
      const x = (i / (scores.length - 1)) * W;
      const y = H - ((v - min) / range) * H;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(" ");
  const last = scores[scores.length - 1];
  const prev = scores[scores.length - 2];
  const color = last > prev ? "#22c55e" : last < prev ? "#ff4d6d" : "#7070a0";
  return (
    <svg width={W} height={H} viewBox={`0 0 ${W} ${H}`}>
      <polyline
        points={pts}
        fill="none"
        stroke={color}
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function arrsColor(score: number) {
  return score < 30 ? "#22c55e" : score < 60 ? "#f5a623" : "#ff4d6d";
}

function geoScoreColor(score: number) {
  return score >= 70 ? "#22c55e" : score >= 45 ? "#f5a623" : "#ff4d6d";
}

const HEALTH_CONFIG: Record<CitationRiskLevel, { color: string; bg: string; border: string }> = {
  healthy:  { color: "#22c55e", bg: "rgba(34,197,94,0.12)",  border: "rgba(34,197,94,0.25)"  },
  watch:    { color: "#f5a623", bg: "rgba(245,166,35,0.12)", border: "rgba(245,166,35,0.25)" },
  critical: { color: "#ff4d6d", bg: "rgba(255,77,109,0.12)", border: "rgba(255,77,109,0.25)" },
};

function CitationHealthBar({ brand, lang }: { brand: DemoBrand; lang: Lang }) {
  const h = brand.citationHealth;
  const cfg = HEALTH_CONFIG[h.riskLevel];
  const healthLabel = h.riskLevel === "healthy"
    ? tx("company", "healthHealthy", lang)
    : h.riskLevel === "watch"
    ? tx("company", "healthWatch", lang)
    : tx("company", "healthCritical", lang);

  const segments = [
    { pct: h.expertReview,   color: "#22c55e", label: tx("company", "sourceExpert", lang) },
    { pct: h.community,      color: "#3b82f6", label: tx("company", "sourceCommunity", lang) },
    { pct: h.retail,         color: "#f5a623", label: tx("company", "sourceRetail", lang) },
    { pct: h.autoGenerated,  color: "#ff4d6d", label: tx("company", "sourceAutoGen", lang) },
  ];

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <span className="text-xs" style={{ color: "#7070a0" }}>{tx("company", "citationSources", lang)}</span>
        <span
          className="text-xs font-bold px-2 py-0.5 rounded-full"
          style={{ color: cfg.color, background: cfg.bg, border: `1px solid ${cfg.border}` }}
        >
          {tx("company", "contentHealth", lang)}: {healthLabel}
        </span>
      </div>

      {/* Stacked bar */}
      <div className="flex h-2 rounded-full overflow-hidden gap-px">
        {segments.map((s) => (
          <div key={s.label} style={{ width: `${s.pct}%`, background: s.color }} />
        ))}
      </div>

      {/* Legend */}
      <div className="flex flex-wrap gap-x-3 gap-y-1">
        {segments.map((s) => (
          <div key={s.label} className="flex items-center gap-1">
            <div className="w-2 h-2 rounded-full shrink-0" style={{ background: s.color }} />
            <span className="text-xs" style={{ color: "#7070a0" }}>{s.pct}% {s.label}</span>
          </div>
        ))}
      </div>

      {/* Auto-gen warning */}
      {h.riskLevel === "critical" && (
        <div
          className="text-xs px-2.5 py-1.5 rounded-lg leading-snug"
          style={{ background: "rgba(255,77,109,0.08)", color: "#ff4d6d", border: "1px solid rgba(255,77,109,0.2)" }}
        >
          ⚠ {tx("company", "autoGenWarning", lang)}
        </div>
      )}
    </div>
  );
}

function GeoScoreRing({ score }: { score: number }) {
  const r = 22;
  const circ = 2 * Math.PI * r;
  const dash = (score / 100) * circ;
  const color = geoScoreColor(score);
  return (
    <svg width="56" height="56" viewBox="0 0 56 56">
      <circle cx="28" cy="28" r={r} fill="none" stroke="#25253f" strokeWidth="4" />
      <circle
        cx="28" cy="28" r={r} fill="none"
        stroke={color} strokeWidth="4"
        strokeDasharray={`${dash} ${circ}`}
        strokeLinecap="round"
        transform="rotate(-90 28 28)"
      />
      <text x="28" y="32" textAnchor="middle" fontSize="11" fontWeight="800" fill={color}>{score}</text>
    </svg>
  );
}

function TrendIcon({ trend }: { trend: DemoBrand["trend"] }) {
  if (trend === "up")   return <span style={{ color: "#22c55e" }}>↑</span>;
  if (trend === "down") return <span style={{ color: "#ff4d6d" }}>↓</span>;
  return <span style={{ color: "#7070a0" }}>→</span>;
}

export default function CompanyDashboardView({
  slug,
  lang,
}: {
  slug: string;
  lang: Lang;
}) {
  const company = DEMO_COMPANIES[slug];
  const base = lang === "zh" ? `/zh/company/${slug}` : `/company/${slug}`;

  if (!company) {
    return (
      <div className="text-center py-24" style={{ color: "#7070a0" }}>
        {tx("company", "notFound", lang)}{" "}
        <Link href={lang === "zh" ? "/zh" : "/"} className="underline" style={{ color: "#ff6b35" }}>
          {tx("company", "back", lang)}
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <Link
            href={lang === "zh" ? "/zh" : "/"}
            className="text-sm hover:text-white transition-colors mb-3 inline-block"
            style={{ color: "#7070a0" }}
          >
            {tx("company", "back", lang)}
          </Link>
          <div className="flex items-center gap-3">
            <h1 className="text-3xl font-black">{company.name}</h1>
            <span
              className="text-xs px-2.5 py-1 rounded-full font-semibold"
              style={{
                background: `${company.planColor}18`,
                color: company.planColor,
                border: `1px solid ${company.planColor}33`,
              }}
            >
              {lang === "zh" ? (company.planZh ?? company.plan) : company.plan}
            </span>
          </div>
          <p className="text-sm mt-1" style={{ color: "#7070a0" }}>
            {company.brands.length} {tx("company", "brandsMonitored", lang)} · {tx("company", "privateWs", lang)}
          </p>
        </div>
        <div className="flex gap-3">
          <Link
            href="/runs/new"
            className="text-sm px-4 py-2 rounded-xl transition-colors hover:text-white"
            style={{ border: "1px solid #25253f", color: "#7070a0" }}
          >
            {tx("company", "runAnalysis", lang)}
          </Link>
          <Link
            href={`${base}/execution`}
            className="text-sm font-semibold px-4 py-2 rounded-xl transition-opacity hover:opacity-85"
            style={{ background: "#ff6b35", color: "#fff" }}
          >
            {tx("company", "viewPlaybook", lang)}
          </Link>
        </div>
      </div>

      {/* KPI cards */}
      <div className="grid grid-cols-3 gap-4">
        <div className="rounded-xl p-5" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
          <div className="text-2xl font-black mb-1" style={{ color: arrsColor(company.avgArrs) }}>
            {company.avgArrs}
          </div>
          <div className="text-xs" style={{ color: "#7070a0" }}>{tx("company", "avgArrs", lang)}</div>
        </div>
        <div className="rounded-xl p-5" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
          <div className="text-2xl font-black mb-1" style={{ color: "#22c55e" }}>
            {company.brandsImproving}/{company.brands.length}
          </div>
          <div className="text-xs" style={{ color: "#7070a0" }}>{tx("company", "brandsImproving", lang)}</div>
        </div>
        <div className="rounded-xl p-5" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
          <div className="text-2xl font-black mb-1" style={{ color: "#f5a623" }}>
            {new Date(company.nextScheduledRun).toLocaleDateString(
              lang === "zh" ? "zh-CN" : "en-US",
              { month: "short", day: "numeric" }
            )}
          </div>
          <div className="text-xs" style={{ color: "#7070a0" }}>{tx("company", "nextScheduled", lang)}</div>
        </div>
      </div>

      {/* Brand cards */}
      <div>
        <h2 className="text-sm font-semibold mb-4 uppercase tracking-widest" style={{ color: "#7070a0" }}>
          {tx("company", "trackedBrands", lang)}
        </h2>
        <div className="grid md:grid-cols-3 gap-4">
          {company.brands.map((brand) => (
            <div
              key={brand.name}
              className="rounded-2xl p-6 space-y-4"
              style={{ background: "#0f0f17", border: "1px solid #25253f" }}
            >
              {/* Brand header */}
              <div className="flex items-start justify-between">
                <div>
                  <div className="font-bold text-lg">{brand.name}</div>
                  <div className="text-xs mt-0.5" style={{ color: "#7070a0" }}>
                    {lang === "zh" ? (brand.categoryZh ?? brand.category) : brand.category}
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-black" style={{ color: arrsColor(brand.arrs) }}>
                    {brand.arrs}
                  </div>
                  <div className="text-xs" style={{ color: "#7070a0" }}>ARRS</div>
                </div>
              </div>

              {/* SOV */}
              <div>
                <div className="flex justify-between text-xs mb-1" style={{ color: "#7070a0" }}>
                  <span>{tx("company", "weightedSov", lang)}</span>
                  <span style={{ color: "#f5a623" }}>{brand.weighted_sov.toFixed(1)}%</span>
                </div>
                <div className="h-1.5 rounded-full overflow-hidden" style={{ background: "#25253f" }}>
                  <div
                    className="h-full rounded-full"
                    style={{ width: `${Math.min(100, brand.weighted_sov * 2)}%`, background: "#f5a623" }}
                  />
                </div>
              </div>

              {/* Trend */}
              <div className="flex items-center gap-1.5 text-sm">
                <TrendIcon trend={brand.trend} />
                <span
                  style={{
                    color: brand.trend === "up" ? "#22c55e" : brand.trend === "down" ? "#ff4d6d" : "#7070a0",
                  }}
                >
                  {lang === "zh" ? (brand.trendDeltaZh ?? brand.trendDelta) : brand.trendDelta}
                </span>
              </div>

              {/* GEO Score + Citation Rate */}
              <div className="flex items-center gap-4 py-1" style={{ borderTop: "1px solid #1a1a2e", borderBottom: "1px solid #1a1a2e" }}>
                <div className="flex items-center gap-2">
                  <GeoScoreRing score={brand.geo_score} />
                  <div>
                    <div className="text-xs font-semibold" style={{ color: "#f0f0f8" }}>
                      {tx("company", "geoScore", lang)}
                    </div>
                    <div className="text-xs" style={{ color: "#7070a0" }}>/100</div>
                  </div>
                </div>
                <div className="ml-auto text-right">
                  <div className="text-xl font-black" style={{ color: "#f5a623" }}>{brand.citation_rate}%</div>
                  <div className="text-xs" style={{ color: "#7070a0" }}>{tx("company", "citationRate", lang)}</div>
                </div>
              </div>

              {/* 4-week GEO trend sparkline */}
              {BRAND_TRENDS[brand.name] && (() => {
                const scores = BRAND_TRENDS[brand.name];
                const delta = scores[scores.length - 1] - scores[0];
                const last  = scores[scores.length - 1];
                const prev  = scores[scores.length - 2];
                const color = last > prev ? "#22c55e" : last < prev ? "#ff4d6d" : "#7070a0";
                return (
                  <div className="flex items-center justify-between px-1">
                    <div className="text-xs" style={{ color: "#7070a0" }}>
                      {lang === "zh" ? "4周 GEO 趋势" : "4-week GEO trend"}
                    </div>
                    <div className="flex items-center gap-2">
                      <GeoTrendLine scores={scores} />
                      <span className="text-xs font-bold tabular-nums" style={{ color }}>
                        {delta > 0 ? "+" : ""}{delta} pts
                      </span>
                    </div>
                  </div>
                );
              })()}

              {/* Sentiment */}
              <div>
                <div className="text-xs mb-2" style={{ color: "#7070a0" }}>{tx("company", "sentiment", lang)}</div>
                <div className="flex gap-2">
                  {[
                    { key: "sentPositive" as const, pct: brand.sentiment.positive, color: "#22c55e" },
                    { key: "sentNeutral" as const,  pct: brand.sentiment.neutral,  color: "#f5a623" },
                    { key: "sentNegative" as const, pct: brand.sentiment.negative, color: "#ff4d6d" },
                  ].map((s) => (
                    <div key={s.key} className="flex-1 text-center rounded-lg py-1.5" style={{ background: `${s.color}12` }}>
                      <div className="text-sm font-bold" style={{ color: s.color }}>{s.pct}%</div>
                      <div className="text-xs" style={{ color: "#7070a0" }}>{tx("company", s.key, lang)}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* SOV by model */}
              <div>
                <div className="text-xs mb-1.5" style={{ color: "#7070a0" }}>{tx("company", "byModel", lang)}</div>
                {[
                  { label: "ChatGPT",    val: brand.by_model.chatgpt },
                  { label: "Claude",     val: brand.by_model.claude },
                  { label: "Gemini",     val: brand.by_model.gemini },
                  { label: "Perplexity", val: brand.by_model.perplexity },
                ].map((m) => (
                  <div key={m.label} className="flex items-center gap-2 mb-1">
                    <div className="text-xs w-16 shrink-0" style={{ color: "#7070a0" }}>{m.label}</div>
                    <div className="flex-1 h-1.5 rounded-full overflow-hidden" style={{ background: "#25253f" }}>
                      <div className="h-full rounded-full" style={{ width: `${Math.min(100, m.val * 2.5)}%`, background: "#f5a623" }} />
                    </div>
                    <div className="text-xs w-10 text-right" style={{ color: "#f5a623" }}>{m.val}%</div>
                  </div>
                ))}
              </div>

              {/* Sample AI Queries */}
              {brand.sampleQueries && brand.sampleQueries.length > 0 && (
                <div>
                  <div className="text-xs mb-2 font-semibold uppercase tracking-widest" style={{ color: "#7070a0" }}>
                    {lang === "zh" ? "AI 实际回答示例" : "What AI Actually Said"}
                  </div>
                  <div className="space-y-2">
                    {brand.sampleQueries.map((q, i) => (
                      <div key={i} className="rounded-lg p-3 space-y-1.5" style={{ background: "#0a0a14", border: "1px solid #1e1e30" }}>
                        <div className="flex items-start justify-between gap-2">
                          <div className="text-xs italic" style={{ color: "#a0a0c8" }}>
                            "{lang === "zh" ? (q.queryZh ?? q.query) : q.query}"
                          </div>
                          {q.brandPosition !== null ? (
                            <div className="shrink-0 text-xs font-bold px-1.5 py-0.5 rounded"
                              style={{
                                background: q.brandPosition === 1 ? "rgba(34,197,94,0.15)" : "rgba(245,166,35,0.12)",
                                color: q.brandPosition === 1 ? "#22c55e" : "#f5a623",
                              }}>
                              #{q.brandPosition}
                            </div>
                          ) : (
                            <div className="shrink-0 text-xs font-bold px-1.5 py-0.5 rounded"
                              style={{ background: "rgba(255,77,109,0.12)", color: "#ff4d6d" }}>
                              {lang === "zh" ? "未提及" : "Not cited"}
                            </div>
                          )}
                        </div>
                        <p className="text-xs leading-relaxed" style={{ color: "#555580", fontStyle: "italic" }}>
                          {lang === "zh" ? (q.snippetZh ?? q.snippet) : q.snippet}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Citation Health */}
              <CitationHealthBar brand={brand} lang={lang} />

              {/* Competitors */}
              <div>
                <div className="text-xs mb-1.5" style={{ color: "#7070a0" }}>{tx("company", "vsCompetitors", lang)}</div>
                <div className="flex flex-wrap gap-1">
                  {brand.competitors.map((c) => (
                    <span
                      key={c}
                      className="text-xs px-2 py-0.5 rounded-full"
                      style={{ background: "#161625", color: "#7070a0", border: "1px solid #25253f" }}
                    >
                      {c}
                    </span>
                  ))}
                </div>
              </div>

              {/* Links */}
              <div className="flex gap-3 pt-1">
                <Link
                  href={`/brands/${encodeURIComponent(brand.name)}`}
                  className="text-xs underline hover:text-white transition-colors"
                  style={{ color: "#7070a0" }}
                >
                  {tx("company", "brandDetail", lang)}
                </Link>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* GEO → Platform Sales Signal (P2) */}
      <div className="rounded-2xl p-6 space-y-5" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
        <div className="flex items-center gap-3 flex-wrap">
          <div className="text-sm font-bold uppercase tracking-widest" style={{ color: "#7070a0" }}>
            {lang === "zh" ? "AI 曝光 → 平台销量传导信号" : "AI Visibility → Platform Sales Signal"}
          </div>
          <span className="text-xs px-2 py-0.5 rounded-full font-medium"
            style={{ background: "rgba(34,197,94,.12)", color: "#22c55e", border: "1px solid rgba(34,197,94,.25)" }}>
            {lang === "zh" ? "实时关联验证" : "Live correlation"}
          </span>
        </div>
        <div className="grid md:grid-cols-3 gap-4">
          {[
            {
              brand: "JumpStart Pro",
              event: lang === "zh" ? "SOV ↑ 8.5% (4周)" : "SOV ↑ 8.5% over 4 wks",
              result: lang === "zh" ? "Amazon 自然流量 +23%" : "Amazon organic sessions +23%",
              lag: lang === "zh" ? "滞后约 6 周" : "~6 week lag",
              color: "#22c55e",
            },
            {
              brand: "MagDrive Pro",
              event: lang === "zh" ? "Wirecutter 引用 0 → 1" : "Wirecutter citation: 0 → 1",
              result: lang === "zh" ? "品牌关键词搜索量 +41%" : "Brand keyword search +41%",
              lag: lang === "zh" ? "引用后第 3 周生效" : "Effective by week 3",
              color: "#f5a623",
            },
            {
              brand: "DriveSafe Pro",
              event: lang === "zh" ? "自动生成内容占比 46%" : "Auto-gen content: 46%",
              result: lang === "zh" ? "AI 引用率下降 60% (3月内)" : "AI citation rate −60% in 3 mo",
              lag: lang === "zh" ? "AI质量过滤升级后" : "After AI quality filter update",
              color: "#ff4d6d",
            },
          ].map(({ brand, event, result, lag, color }) => (
            <div key={brand} className="rounded-xl p-4 space-y-2"
              style={{ background: "#0a0a14", border: `1px solid ${color}25` }}>
              <div className="text-xs font-semibold" style={{ color }}>{brand}</div>
              <div className="text-xs" style={{ color: "#a0a0c8" }}>{event}</div>
              <div className="text-sm font-bold" style={{ color }}>{result}</div>
              <div className="text-xs" style={{ color: "#7070a0" }}>{lag}</div>
            </div>
          ))}
        </div>
        <p className="text-xs" style={{ color: "#555580" }}>
          {lang === "zh"
            ? "数据来源：AutoCore Global 账户内部监控数据，2026年1月–3月"
            : "Source: AutoCore Global internal monitoring data, Jan–Mar 2026"}
        </p>
      </div>

      {/* Demo navigation (P0.1) */}
      <div>
        <div className="text-xs font-bold uppercase tracking-widest mb-4" style={{ color: "#7070a0" }}>
          {lang === "zh" ? "继续探索产品功能" : "Continue the demo"}
        </div>
        <div className="grid md:grid-cols-3 gap-3">
          {[
            {
              href: `${base}/execution`,
              icon: "◈",
              title: lang === "zh" ? "执行手册" : "Execution Playbook",
              desc: lang === "zh" ? "查看具体 GEO 优化行动方案、OKR 跟踪和媒体外联状态" : "See the GEO action plan, OKR tracking, and media outreach status",
            },
            {
              href: lang === "zh" ? "/zh/selection" : "/selection",
              icon: "◎",
              title: lang === "zh" ? "AI 选品情报" : "AI Selection Intel",
              desc: lang === "zh" ? "AI 正在向买家推荐哪些品类——比竞品早 6–8 周看到信号" : "Which categories AI is pushing to buyers — 6–8 weeks before it shows up as sales",
            },
            {
              href: lang === "zh" ? "/zh/optimizer" : "/optimizer",
              icon: "◐",
              title: lang === "zh" ? "成本优化器" : "Cost Optimizer",
              desc: lang === "zh" ? "算出你现有运营成本里有多少可以腾出来投入 GEO" : "Calculate how much of your current ops budget can fund GEO monitoring",
            },
          ].map(({ href, icon, title, desc }) => (
            <Link
              key={href} href={href}
              className="rounded-xl p-4 flex items-start gap-3 transition-all group"
              style={{ background: "#0f0f17", border: "1px solid #25253f" }}
            >
              <span className="text-xl mt-0.5 shrink-0" style={{ color: "#ff6b35" }}>{icon}</span>
              <div>
                <div className="text-sm font-semibold transition-colors group-hover:text-white">{title}</div>
                <div className="text-xs mt-1 leading-relaxed" style={{ color: "#7070a0" }}>{desc}</div>
                <div className="text-xs mt-2 font-medium" style={{ color: "#ff6b35" }}>→</div>
              </div>
            </Link>
          ))}
        </div>
      </div>

      {/* CTA */}
      <div
        className="rounded-2xl p-8 flex items-center justify-between gap-6"
        style={{ background: "linear-gradient(135deg, #0f0f17 0%, #161625 100%)", border: "1px solid #25253f" }}
      >
        <div>
          <p className="font-bold text-lg mb-1">{tx("company", "readyTitle", lang)}</p>
          <p className="text-sm" style={{ color: "#7070a0" }}>
            {tx("company", "readyDesc", lang)
              .replace("{briefs}", "6")
              .replace("{citations}", "8")}
          </p>
        </div>
        <Link
          href={`${base}/execution`}
          className="shrink-0 px-6 py-3 rounded-xl text-sm font-semibold transition-opacity hover:opacity-85"
          style={{ background: "#ff6b35", color: "#fff" }}
        >
          {tx("company", "openPlaybook", lang)}
        </Link>
      </div>
    </div>
  );
}
