import Link from "next/link";
import { api, Run, RunSnapshot, Recommendation } from "@/lib/api";

const CALENDLY = "https://calendly.com/qw2379/geo-chat";
import TrendChart from "./TrendChart";

const priorityStyle: Record<string, { bg: string; color: string }> = {
  high:   { bg: "rgba(255,77,109,0.12)",  color: "#ff4d6d" },
  medium: { bg: "rgba(245,166,35,0.12)",  color: "#f5a623" },
  low:    { bg: "rgba(34,197,94,0.12)",   color: "#22c55e" },
};

function statusStyle(s: string) {
  if (s === "done")    return { bg: "rgba(34,197,94,0.12)",  color: "#22c55e" };
  if (s === "running") return { bg: "rgba(255,107,53,0.12)", color: "#ff6b35" };
  if (s === "failed")  return { bg: "rgba(255,77,109,0.12)", color: "#ff4d6d" };
  return { bg: "rgba(245,166,35,0.12)", color: "#f5a623" };
}

export default async function BrandPage({
  params,
}: {
  params: Promise<{ brand: string }>;
}) {
  const { brand } = await params;
  const brandName = decodeURIComponent(brand);

  const [runs, trends] = await Promise.all([
    api.listRuns(brandName).catch(() => [] as Run[]),
    api.getBrandTrends(brandName, 90).catch(() => [] as RunSnapshot[]),
  ]);

  // Get latest completed run for recommendations
  const latestDone = runs.find((r) => r.status === "done");
  let recommendations: Recommendation | null = null;
  if (latestDone) {
    recommendations = await api.getRecommendations(latestDone.id).catch(() => null);
  }

  // Latest snapshot for KPI cards
  const latest = trends.at(-1);

  return (
    <div className="space-y-8">
      <div className="flex items-center gap-3">
        <Link href="/dashboard" className="text-sm transition-colors hover:text-white" style={{ color: "#7070a0" }}>
          ← Dashboard
        </Link>
        <span style={{ color: "#25253f" }}>/</span>
        <h1 className="text-2xl font-bold">{brandName}</h1>
      </div>

      {/* KPI cards — asymmetric 1+3 */}
      {latest && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {/* ARRS — prominent */}
          <div
            className="md:col-span-1 rounded-xl p-5"
            style={{ background: "#0f0f17", border: "1px solid #25253f" }}
          >
            <div className="text-3xl font-black mb-1" style={{ color: "#f5a623" }}>
              {latest.arrs.toFixed(0)}
            </div>
            <div className="text-sm font-semibold mb-0.5">ARRS Score</div>
            <div className="text-xs" style={{ color: "#7070a0" }}>Risk score (0–100)</div>
          </div>
          {[
            { label: "Weighted SOV", value: `${latest.weighted_sov.toFixed(1)}%`, note: "Weighted share of voice" },
            { label: "SOV High Intent", value: `${latest.sov_high.toFixed(1)}%`, note: "High-intent queries" },
            { label: "Mentions", value: `${latest.mention_count}/${latest.total_prompts}`, note: "Out of total prompts" },
          ].map((kpi) => (
            <div
              key={kpi.label}
              className="rounded-xl p-5"
              style={{ background: "#0f0f17", border: "1px solid #25253f" }}
            >
              <div className="text-2xl font-bold mb-1">{kpi.value}</div>
              <div className="text-sm font-medium mb-0.5">{kpi.label}</div>
              <div className="text-xs" style={{ color: "#7070a0" }}>{kpi.note}</div>
            </div>
          ))}
        </div>
      )}

      {/* Trend chart */}
      <div className="rounded-xl p-6" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
        <h2 className="font-semibold mb-4">SOV &amp; ARRS over time</h2>
        <TrendChart data={trends} />
      </div>

      {/* Recommendations */}
      {recommendations && recommendations.items.length > 0 && (
        <div className="rounded-xl p-6" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
          <h2 className="font-semibold mb-1">AI Recommendations</h2>
          <p className="text-xs mb-4" style={{ color: "#7070a0" }}>
            Generated by {recommendations.model_used} ·{" "}
            {new Date(recommendations.generated_at).toLocaleDateString()}
          </p>
          <div className="space-y-3">
            {recommendations.items.map((item, i) => {
              const ps = priorityStyle[item.priority] ?? { bg: "rgba(112,112,160,0.12)", color: "#7070a0" };
              return (
                <div
                  key={i}
                  className="flex gap-3 p-4 rounded-xl"
                  style={{ background: "#161625" }}
                >
                  <span
                    className="text-xs px-2 py-0.5 rounded-full font-medium h-fit mt-0.5 shrink-0"
                    style={{ background: ps.bg, color: ps.color }}
                  >
                    {item.priority}
                  </span>
                  <div>
                    <div className="font-medium text-sm">{item.title}</div>
                    <div className="text-xs mt-0.5" style={{ color: "#7070a0" }}>{item.description}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Book a call CTA */}
      {latest && (
        <div
          className="rounded-2xl p-8 text-center"
          style={{
            background: "linear-gradient(135deg, #0f0f17 0%, #161625 100%)",
            border: "1px solid #ff6b35",
          }}
        >
          <p className="font-bold text-lg mb-2">Want to move these numbers?</p>
          <p className="text-sm mb-6" style={{ color: "#7070a0" }}>
            We identify exactly which content signals are holding your brand back — and build the plan to fix them.
          </p>
          <a
            href={CALENDLY}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-semibold transition-opacity hover:opacity-85"
            style={{ background: "#ff6b35", color: "#fff" }}
          >
            Book a free strategy call →
          </a>
        </div>
      )}

      {/* Recent runs */}
      {runs.length > 0 && (
        <div className="rounded-xl overflow-hidden" style={{ border: "1px solid #25253f" }}>
          <div className="px-4 py-3 font-semibold text-sm" style={{ background: "#161625", borderBottom: "1px solid #25253f" }}>
            Recent runs
          </div>
          <table className="w-full text-sm">
            <thead className="text-xs uppercase tracking-wide" style={{ background: "#161625", color: "#7070a0" }}>
              <tr>
                <th className="text-left px-4 py-2">Status</th>
                <th className="text-left px-4 py-2">Providers</th>
                <th className="text-left px-4 py-2">Prompts</th>
                <th className="text-left px-4 py-2">Date</th>
                <th className="px-4 py-2" />
              </tr>
            </thead>
            <tbody style={{ background: "#0f0f17" }}>
              {runs.map((run) => {
                const ss = statusStyle(run.status);
                return (
                  <tr key={run.id} style={{ borderTop: "1px solid #25253f" }}>
                    <td className="px-4 py-2">
                      <span
                        className="text-xs px-2 py-0.5 rounded-full font-medium"
                        style={{ background: ss.bg, color: ss.color }}
                      >
                        {run.status}
                      </span>
                    </td>
                    <td className="px-4 py-2" style={{ color: "#7070a0" }}>{run.providers.join(", ")}</td>
                    <td className="px-4 py-2" style={{ color: "#7070a0" }}>{run.num_prompts}</td>
                    <td className="px-4 py-2 text-xs" style={{ color: "#7070a0" }}>
                      {new Date(run.created_at).toLocaleDateString()}
                    </td>
                    <td className="px-4 py-2 text-right">
                      <Link
                        href={`/runs/${run.id}`}
                        className="text-xs underline transition-colors hover:text-white"
                        style={{ color: "#7070a0" }}
                      >
                        View
                      </Link>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
