"use client";

import { useState } from "react";
import Link from "next/link";

interface CitationBreakdown {
  type: string;
  label: string;
  percent: number;
  examples: string[];
  color: string;
  icon: string;
  riskTag?: string;
}

interface HealthResult {
  brand: string;
  category: string;
  scannedAt: string;
  riskLevel: "critical" | "warning" | "healthy";
  score: number;
  breakdown: CitationBreakdown[];
  insight: string;
  recommendations: string[];
}

const DEMO_RESULTS: Record<string, HealthResult> = {
  "jumpstart pro": {
    brand: "JumpStart Pro",
    category: "Automotive Accessories",
    scannedAt: "2025-01-27",
    riskLevel: "critical",
    score: 31,
    breakdown: [
      {
        type: "expertReview",
        label: "Expert Review Citations",
        percent: 22,
        examples: ["Wirecutter (0)", "Car and Driver (0)", "Motor Trend (0)"],
        color: "#22c55e",
        icon: "🏆",
      },
      {
        type: "community",
        label: "Community & Forum Mentions",
        percent: 15,
        examples: ["Reddit r/CarTalk (3 threads)", "Amazon Q&A (12 answers)"],
        color: "#f5a623",
        icon: "💬",
      },
      {
        type: "retail",
        label: "Retail & Listing Content",
        percent: 41,
        examples: ["Amazon product description", "Walmart listing", "Brand website"],
        color: "#7070a0",
        icon: "🛒",
        riskTag: "At risk",
      },
      {
        type: "autoGenerated",
        label: "Auto-Generated Content",
        percent: 22,
        examples: ["Anonymous blog posts (8)", "SEO article farms (14)", "Unattributed reviews"],
        color: "#ff4d6d",
        icon: "⚠",
        riskTag: "Critical",
      },
    ],
    insight:
      "22% of AI citations for JumpStart Pro originate from auto-generated content — above the 20% critical threshold. With recent AI quality filter upgrades from DeepSeek and ChatGPT, these low-quality citations are actively being downgraded. The brand has zero expert review placements in major automotive publications.",
    recommendations: [
      "Commission expert reviews in Car and Driver, Motor Trend, or Wirecutter — expert-attributed content gets 4× AI citation weight",
      "Publish verifiable performance benchmarks: cranking amps test results, temperature range PDFs",
      "Build structured FAQ content addressing specific buyer questions (diesel engines, cold weather, truck use cases)",
    ],
  },
  "noco gb40": {
    brand: "NOCO Boost Plus GB40",
    category: "Car Jump Starters",
    scannedAt: "2025-01-27",
    riskLevel: "healthy",
    score: 82,
    breakdown: [
      {
        type: "expertReview",
        label: "Expert Review Citations",
        percent: 54,
        examples: ["Wirecutter (Best Jump Starter)", "Car and Driver (Top Pick)", "Popular Mechanics"],
        color: "#22c55e",
        icon: "🏆",
      },
      {
        type: "community",
        label: "Community & Forum Mentions",
        percent: 28,
        examples: ["Reddit r/Cartalk (87 threads)", "Amazon Q&A (340+ answers)", "YouTube reviews"],
        color: "#f5a623",
        icon: "💬",
      },
      {
        type: "retail",
        label: "Retail & Listing Content",
        percent: 14,
        examples: ["Amazon product description", "AutoZone listing"],
        color: "#7070a0",
        icon: "🛒",
      },
      {
        type: "autoGenerated",
        label: "Auto-Generated Content",
        percent: 4,
        examples: ["2 low-authority blog mentions"],
        color: "#ff4d6d",
        icon: "⚠",
      },
    ],
    insight:
      "NOCO GB40 has excellent citation health. 54% of AI citations come from major expert publications — Wirecutter, Car and Driver, and Popular Mechanics all name it Best Pick. Auto-generated content is minimal at only 4%. This is the gold standard for AI-safe citation profile.",
    recommendations: [
      "Maintain expert review relationships — proactively pitch new product iterations",
      "Expand community presence in international markets (UK, Germany) where AI citation gaps exist",
      "Monitor for citation dilution as new competitors enter the category",
    ],
  },
  "vantrue n4 pro": {
    brand: "Vantrue N4 Pro",
    category: "Dash Cameras",
    scannedAt: "2025-01-27",
    riskLevel: "warning",
    score: 57,
    breakdown: [
      {
        type: "expertReview",
        label: "Expert Review Citations",
        percent: 31,
        examples: ["The Verge (Recommended)", "TechRadar", "Wirecutter (consideration)"],
        color: "#22c55e",
        icon: "🏆",
      },
      {
        type: "community",
        label: "Community & Forum Mentions",
        percent: 29,
        examples: ["Reddit r/dashcams (45 threads)", "YouTube unboxings (12 videos)"],
        color: "#f5a623",
        icon: "💬",
      },
      {
        type: "retail",
        label: "Retail & Listing Content",
        percent: 24,
        examples: ["Amazon listing", "Best Buy product page", "B&H Photo"],
        color: "#7070a0",
        icon: "🛒",
      },
      {
        type: "autoGenerated",
        label: "Auto-Generated Content",
        percent: 16,
        examples: ["7 SEO comparison articles", "5 affiliate roundup posts"],
        color: "#ff4d6d",
        icon: "⚠",
        riskTag: "Watch",
      },
    ],
    insight:
      "Vantrue N4 Pro is in the warning zone. 16% auto-generated content is below the critical threshold but trending upward as affiliate SEO sites have started auto-generating comparison content. Expert review presence is solid but needs reinforcement.",
    recommendations: [
      "Proactively get a Wirecutter main-pick placement — currently only in consideration tier",
      "Monitor affiliate content farms — request removal of low-quality automated reviews",
      "Publish 3-channel recording technical spec sheet with independent lab verification",
    ],
  },
};

const RISK_CONFIG = {
  critical: {
    label: "CRITICAL",
    color: "#ff4d6d",
    bg: "rgba(255,77,109,0.08)",
    border: "rgba(255,77,109,0.3)",
    desc: "High risk of AI citation removal",
  },
  warning: {
    label: "WARNING",
    color: "#f5a623",
    bg: "rgba(245,166,35,0.08)",
    border: "rgba(245,166,35,0.3)",
    desc: "Monitor closely — trending toward risk",
  },
  healthy: {
    label: "HEALTHY",
    color: "#22c55e",
    bg: "rgba(34,197,94,0.08)",
    border: "rgba(34,197,94,0.3)",
    desc: "Strong citation profile",
  },
};

function ScoreGauge({ score, color }: { score: number; color: string }) {
  const r = 40;
  const circ = 2 * Math.PI * r;
  const dash = (score / 100) * circ;
  return (
    <svg width={100} height={100} viewBox="0 0 100 100">
      <circle cx={50} cy={50} r={r} fill="none" stroke="#1a1a2e" strokeWidth={10} />
      <circle
        cx={50} cy={50} r={r} fill="none"
        stroke={color} strokeWidth={10}
        strokeDasharray={`${dash} ${circ - dash}`}
        strokeDashoffset={circ / 4}
        strokeLinecap="round"
        style={{ transition: "stroke-dasharray 0.6s ease" }}
      />
      <text x={50} y={50} textAnchor="middle" dominantBaseline="central" fill="#f0f0f8" fontSize={18} fontWeight={700}>
        {score}
      </text>
      <text x={50} y={65} textAnchor="middle" fill="#7070a0" fontSize={8} fontWeight={500}>
        /100
      </text>
    </svg>
  );
}

export default function ContentHealthPage() {
  const [input, setInput] = useState("JumpStart Pro");
  const [result, setResult] = useState<HealthResult | null>(DEMO_RESULTS["jumpstart pro"]);
  const [checking, setChecking] = useState(false);

  function handleCheck(e: React.FormEvent) {
    e.preventDefault();
    const key = input.trim().toLowerCase();
    setChecking(true);
    setTimeout(() => {
      const found = DEMO_RESULTS[key];
      if (found) {
        setResult(found);
      } else {
        // Generate a generic result for unknown brands
        setResult({
          brand: input.trim(),
          category: "General",
          scannedAt: "2025-01-27",
          riskLevel: "warning",
          score: 44,
          breakdown: [
            { type: "expertReview", label: "Expert Review Citations", percent: 18, examples: ["No major publications found"], color: "#22c55e", icon: "🏆" },
            { type: "community", label: "Community & Forum Mentions", percent: 24, examples: ["Some Reddit/forum mentions"], color: "#f5a623", icon: "💬" },
            { type: "retail", label: "Retail & Listing Content", percent: 40, examples: ["Product listings detected"], color: "#7070a0", icon: "🛒", riskTag: "At risk" },
            { type: "autoGenerated", label: "Auto-Generated Content", percent: 18, examples: ["Multiple SEO articles detected"], color: "#ff4d6d", icon: "⚠", riskTag: "Watch" },
          ],
          insight: `${input.trim()} shows a common mid-tier citation profile. Expert review presence is below average — most AI citations currently come from retail listings and auto-generated SEO content, which are the most vulnerable to AI quality filter upgrades.`,
          recommendations: [
            "Identify 3 relevant expert publications in your category and pitch product for review",
            "Create verifiable technical documentation with measurable specs",
            "Build structured community presence in forums and Q&A platforms",
          ],
        });
      }
      setChecking(false);
    }, 1200);
  }

  const riskCfg = result ? RISK_CONFIG[result.riskLevel] : null;

  return (
    <div className="max-w-4xl mx-auto px-4 py-10 space-y-8">
      {/* Header */}
      <div>
        <div
          className="inline-block text-xs font-semibold uppercase tracking-widest px-3 py-1 rounded-full mb-4"
          style={{ background: "rgba(255,77,109,0.12)", color: "#ff4d6d", border: "1px solid rgba(255,77,109,0.25)" }}
        >
          Citation Health Diagnostic
        </div>
        <h1 className="text-3xl font-black mb-2">Where Are Your AI Citations Coming From?</h1>
        <p className="text-sm leading-relaxed max-w-2xl" style={{ color: "#9090b0" }}>
          AI models don&apos;t treat all content equally. Citations from expert reviews carry 4× more weight than retail
          listings — and auto-generated content is being actively filtered out. See your brand&apos;s citation source
          breakdown.
        </p>
      </div>

      {/* Input */}
      <form
        onSubmit={handleCheck}
        className="flex gap-3 flex-wrap"
      >
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Enter brand or product name (e.g. JumpStart Pro, NOCO GB40)"
          className="flex-1 min-w-64 rounded-xl px-4 py-3 text-sm outline-none"
          style={{ background: "#0f0f17", border: "1px solid #25253f", color: "#f0f0f8" }}
        />
        <button
          type="submit"
          disabled={checking || !input.trim()}
          className="px-6 py-3 rounded-xl text-sm font-semibold transition-opacity hover:opacity-85 disabled:opacity-50"
          style={{ background: "#ff4d6d", color: "#fff" }}
        >
          {checking ? "Analyzing…" : "Check Citation Health →"}
        </button>
      </form>

      {/* Demo note */}
      <p className="text-xs" style={{ color: "#4a4a6a" }}>
        Try: &quot;JumpStart Pro&quot;, &quot;NOCO GB40&quot;, &quot;Vantrue N4 Pro&quot; · Full real-time analysis available with a free account
      </p>

      {/* Result */}
      {result && riskCfg && (
        <div className="space-y-6">
          {/* Risk header */}
          <div
            className="rounded-2xl p-6 flex flex-col md:flex-row items-start md:items-center gap-6"
            style={{ background: riskCfg.bg, border: `1px solid ${riskCfg.border}` }}
          >
            <ScoreGauge score={result.score} color={riskCfg.color} />
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-1">
                <span
                  className="text-xs font-bold uppercase tracking-widest px-3 py-1 rounded-full"
                  style={{ background: riskCfg.bg, color: riskCfg.color, border: `1px solid ${riskCfg.border}` }}
                >
                  {riskCfg.label}
                </span>
                <span className="text-xs" style={{ color: "#7070a0" }}>{riskCfg.desc}</span>
              </div>
              <h2 className="text-xl font-bold mb-1">{result.brand}</h2>
              <p className="text-xs mb-3" style={{ color: "#7070a0" }}>
                {result.category} · Scanned {result.scannedAt}
              </p>
              <p className="text-sm leading-relaxed" style={{ color: "#9090b0" }}>{result.insight}</p>
            </div>
          </div>

          {/* Citation breakdown */}
          <div className="rounded-2xl overflow-hidden" style={{ border: "1px solid #25253f" }}>
            <div className="px-6 py-4" style={{ background: "#0f0f17", borderBottom: "1px solid #25253f" }}>
              <h3 className="font-semibold text-sm">Citation Source Breakdown</h3>
              <p className="text-xs mt-0.5" style={{ color: "#7070a0" }}>
                Based on analysis of AI model responses across 100 queries in this category
              </p>
            </div>

            {/* Visual bar */}
            <div className="px-6 pt-5 pb-4" style={{ background: "#0a0a12" }}>
              <div className="flex rounded-lg overflow-hidden h-4 gap-0.5 mb-2">
                {result.breakdown.map((b) => (
                  <div
                    key={b.type}
                    style={{ width: `${b.percent}%`, background: b.color, opacity: 0.85 }}
                    title={`${b.label}: ${b.percent}%`}
                  />
                ))}
              </div>
              <div className="flex flex-wrap gap-3">
                {result.breakdown.map((b) => (
                  <div key={b.type} className="flex items-center gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-sm" style={{ background: b.color }} />
                    <span className="text-xs" style={{ color: "#7070a0" }}>{b.label} <strong style={{ color: "#f0f0f8" }}>{b.percent}%</strong></span>
                  </div>
                ))}
              </div>
            </div>

            {/* Detail rows */}
            <div className="divide-y" style={{ borderTop: "1px solid #1a1a2e" }}>
              {result.breakdown.map((b) => (
                <div
                  key={b.type}
                  className="px-6 py-4 flex items-start gap-4"
                  style={{ background: "#0a0a12" }}
                >
                  <div className="text-xl shrink-0 mt-0.5">{b.icon}</div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-sm font-semibold" style={{ color: "#f0f0f8" }}>{b.label}</span>
                      {b.riskTag && (
                        <span
                          className="text-xs px-2 py-0.5 rounded-full font-medium"
                          style={{
                            background: b.riskTag === "Critical" ? "rgba(255,77,109,0.12)" : "rgba(245,166,35,0.12)",
                            color: b.riskTag === "Critical" ? "#ff4d6d" : "#f5a623",
                          }}
                        >
                          {b.riskTag}
                        </span>
                      )}
                    </div>
                    <div className="text-xs" style={{ color: "#7070a0" }}>{b.examples.join(" · ")}</div>
                  </div>
                  <div className="shrink-0 text-right">
                    <div className="text-2xl font-black" style={{ color: b.color }}>{b.percent}%</div>
                    <div className="w-16 h-1.5 rounded-full mt-1 overflow-hidden" style={{ background: "#1a1a2e" }}>
                      <div
                        className="h-full rounded-full"
                        style={{ width: `${b.percent}%`, background: b.color }}
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Recommendations */}
          <div className="rounded-2xl p-6 space-y-4" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
            <h3 className="font-semibold text-sm">Recommended Actions</h3>
            <div className="space-y-3">
              {result.recommendations.map((r, i) => (
                <div key={i} className="flex gap-3">
                  <div
                    className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold mt-0.5"
                    style={{ background: "rgba(255,107,53,0.15)", color: "#ff6b35" }}
                  >
                    {i + 1}
                  </div>
                  <p className="text-sm leading-relaxed" style={{ color: "#9090b0" }}>{r}</p>
                </div>
              ))}
            </div>
          </div>

          {/* CTA */}
          <div
            className="rounded-2xl p-6 flex flex-col md:flex-row items-start md:items-center gap-5"
            style={{ background: "rgba(255,107,53,0.06)", border: "1px solid rgba(255,107,53,0.2)" }}
          >
            <div className="flex-1">
              <div className="font-semibold mb-1">Get your real citation health score</div>
              <p className="text-sm" style={{ color: "#9090b0" }}>
                This is a demo. Run a live scan to see actual AI model responses, real citation sources, and weekly
                tracking for your brand.
              </p>
            </div>
            <div className="flex gap-3 shrink-0 flex-wrap">
              <Link
                href="/audit"
                className="px-5 py-2.5 rounded-xl text-sm font-semibold transition-opacity hover:opacity-85"
                style={{ background: "#ff6b35", color: "#fff" }}
              >
                Run Free Audit →
              </Link>
              <Link
                href="/signup"
                className="px-5 py-2.5 rounded-xl text-sm font-medium transition-opacity hover:opacity-80"
                style={{ border: "1px solid #25253f", color: "#f0f0f8" }}
              >
                Sign up free
              </Link>
            </div>
          </div>
        </div>
      )}

      {/* Three Standards explainer */}
      <div className="rounded-2xl p-6 space-y-4" style={{ background: "#0f0f17", border: "1px solid #25253f" }}>
        <div className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#ff6b35" }}>
          The Three Standards of Healthy AI Citations
        </div>
        <div className="grid md:grid-cols-3 gap-4">
          {[
            {
              icon: "①",
              title: "Real Experts",
              desc: "Content authored or verified by domain experts. AI models weight expert-attributed content 4× higher than anonymous sources.",
              color: "#22c55e",
            },
            {
              icon: "②",
              title: "Real Data",
              desc: "Technical specs with publicly verifiable test sources — PDFs, lab certifications, independent benchmarks. AI prefers factual, data-backed claims.",
              color: "#f5a623",
            },
            {
              icon: "③",
              title: "Real Structure",
              desc: "Content that follows buyer decision journeys — comparison, use-case, problem-solution. Structured content gets 2.3× more AI citations.",
              color: "#ff6b35",
            },
          ].map((s) => (
            <div key={s.icon} className="space-y-2">
              <div className="text-2xl font-black" style={{ color: s.color }}>{s.icon}</div>
              <div className="font-semibold text-sm">{s.title}</div>
              <p className="text-xs leading-relaxed" style={{ color: "#7070a0" }}>{s.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
