export interface SampleQuery {
  query: string;
  queryZh?: string;
  brandPosition: number | null; // null = not mentioned
  snippet: string;              // what AI actually said about this brand
  snippetZh?: string;
}

export type CitationRiskLevel = "healthy" | "watch" | "critical";

export interface CitationHealth {
  expertReview: number;    // % from expert/review sites (Wirecutter, PCMag, YouTube reviewers)
  community: number;       // % from Reddit, forums, user discussions
  retail: number;          // % from retailer pages (Amazon, product listings)
  autoGenerated: number;   // % from low-quality auto-generated content — RISK
  riskLevel: CitationRiskLevel;
}

export interface DemoBrand {
  name: string;
  category: string;
  categoryZh?: string;
  arrs: number;
  weighted_sov: number;
  sov_high: number;
  trend: "up" | "down" | "stable";
  trendDelta: string;
  trendDeltaZh?: string;
  lastRun: string;
  competitors: string[];
  // Topify-inspired metrics
  geo_score: number;          // 0–100 composite GEO score
  citation_rate: number;      // % of AI responses that cite a source
  sentiment: { positive: number; neutral: number; negative: number };
  by_model: { chatgpt: number; claude: number; perplexity: number; gemini: number };
  sampleQueries: SampleQuery[];
  citationHealth: CitationHealth; // source quality breakdown
}

export interface DemoCompany {
  slug: string;
  name: string;
  plan: string;
  planZh?: string;
  planColor: string;
  avgArrs: number;
  brandsImproving: number;
  nextScheduledRun: string;
  brands: DemoBrand[];
}

export type ContentStatus = "draft" | "published" | "measuring";

export interface ContentBrief {
  id: string;
  title: string;
  titleZh?: string;
  targetKeyword: string;
  aiFormat: string;
  aiFormatZh?: string;
  status: ContentStatus;
  brand: string;
  dueDate: string;
}

export interface CitationTarget {
  id: string;
  publication: string;
  domainAuthority: number;
  relevance: "high" | "medium";
  status: "not started" | "outreach sent" | "in negotiation" | "published";
  targetBrands: string[];
  notes: string;
  notesZh?: string;
}

export interface OKR {
  id: string;
  objective: string;
  objectiveZh?: string;
  keyResult: string;
  keyResultZh?: string;
  current: number;
  target: number;
  startVal: number; // original value (for lower-is-better OKRs)
  unit: string;
  lowerIsBetter: boolean;
  dueDate: string;
  status: "on track" | "at risk" | "achieved";
}

export type ActionPriority = "urgent" | "high" | "medium";

export interface NextAction {
  id: string;
  title: string;
  titleZh?: string;
  description: string;
  descriptionZh?: string;
  priority: ActionPriority;
  assignee: string;
  dueDate: string;
  relatedBrand: string;
  done: boolean;
}

export interface ExecutionPlaybook {
  contentBriefs: ContentBrief[];
  citationTargets: CitationTarget[];
  okrs: OKR[];
  nextActions: NextAction[];
}

// ── Seed Data ─────────────────────────────────────────────────────────────────

export const DEMO_COMPANIES: Record<string, DemoCompany> = {
  "techvision-pro": {
    slug: "techvision-pro",
    name: "TechVision Pro",
    plan: "Execution Tier",
    planZh: "执行计划",
    planColor: "#f5a623",
    avgArrs: 38,
    brandsImproving: 2,
    nextScheduledRun: "2026-03-03T09:00:00Z",
    brands: [
      {
        name: "VoltEdge",
        category: "Portable Power Stations",
        categoryZh: "便携储能站",
        arrs: 42,
        weighted_sov: 18.4,
        sov_high: 22.1,
        trend: "up",
        trendDelta: "+4.2 pts this month",
        trendDeltaZh: "本月 +4.2 分",
        lastRun: "2026-02-24T08:00:00Z",
        competitors: ["Jackery", "EcoFlow", "Bluetti"],
        geo_score: 64,
        citation_rate: 41,
        sentiment: { positive: 58, neutral: 31, negative: 11 },
        by_model: { chatgpt: 21.3, claude: 16.8, perplexity: 17.1, gemini: 18.4 },
        sampleQueries: [
          {
            query: "What's the best portable power station for camping under $600?",
            queryZh: "600美元以内露营最佳便携储能站是哪款？",
            brandPosition: 3,
            snippet: "VoltEdge 500 is a solid mid-range option — decent capacity and reliable LFP cells, though it trails EcoFlow on fast-charging speed.",
            snippetZh: "VoltEdge 500 是不错的中端选择——容量可靠、LFP电芯耐用，但快充速度落后于 EcoFlow。",
          },
          {
            query: "Best solar generator for van life 2026",
            queryZh: "2026年房车生活最佳太阳能发电机",
            brandPosition: null,
            snippet: "VoltEdge was not mentioned in this response. EcoFlow, Jackery, and Bluetti dominated.",
            snippetZh: "本次回答未提及 VoltEdge。EcoFlow、Jackery 和 Bluetti 占据主导。",
          },
        ],
        citationHealth: { expertReview: 42, community: 33, retail: 20, autoGenerated: 5, riskLevel: "healthy" },
      },
      {
        name: "LumaPulse",
        category: "Smart Home Devices",
        categoryZh: "智能家居设备",
        arrs: 61,
        weighted_sov: 9.7,
        sov_high: 7.3,
        trend: "down",
        trendDelta: "−2.1 pts this month",
        trendDeltaZh: "本月 −2.1 分",
        lastRun: "2026-02-24T08:00:00Z",
        competitors: ["Philips Hue", "LIFX", "Nanoleaf"],
        geo_score: 31,
        citation_rate: 18,
        sentiment: { positive: 34, neutral: 41, negative: 25 },
        by_model: { chatgpt: 11.2, claude: 8.4, perplexity: 9.5, gemini: 10.1 },
        sampleQueries: [
          {
            query: "Best smart lights compatible with Apple HomeKit 2026",
            queryZh: "2026年兼容 Apple HomeKit 的最佳智能灯",
            brandPosition: null,
            snippet: "LumaPulse was not mentioned. Philips Hue, Nanoleaf, and LIFX were recommended unanimously.",
            snippetZh: "本次回答未提及 LumaPulse。Philips Hue、Nanoleaf 和 LIFX 获得一致推荐。",
          },
          {
            query: "Affordable smart home lighting for apartments",
            queryZh: "适合公寓的实惠智能家居照明",
            brandPosition: 4,
            snippet: "LumaPulse offers budget-friendly strips but setup reviews are mixed — pairing issues noted on Amazon.",
            snippetZh: "LumaPulse 提供价格实惠的灯带，但设置评价不一——Amazon 上多有配对问题反馈。",
          },
        ],
        citationHealth: { expertReview: 14, community: 22, retail: 27, autoGenerated: 37, riskLevel: "critical" },
      },
      {
        name: "ChargeFast",
        category: "USB-C Chargers",
        categoryZh: "USB-C 充电器",
        arrs: 11,
        weighted_sov: 31.8,
        sov_high: 38.5,
        trend: "up",
        trendDelta: "+7.9 pts this month",
        trendDeltaZh: "本月 +7.9 分",
        lastRun: "2026-02-24T08:00:00Z",
        competitors: ["Anker", "Belkin", "Spigen"],
        geo_score: 82,
        citation_rate: 67,
        sentiment: { positive: 79, neutral: 17, negative: 4 },
        by_model: { chatgpt: 34.2, claude: 29.7, perplexity: 31.5, gemini: 32.1 },
        sampleQueries: [
          {
            query: "Best USB-C charger for MacBook Pro 2026",
            queryZh: "2026年 MacBook Pro 最佳 USB-C 充电器",
            brandPosition: 1,
            snippet: "ChargeFast's 140W GaN charger is the top pick — compact, fast, and MFi-certified. Reviewers consistently praise the build quality.",
            snippetZh: "ChargeFast 140W GaN 充电器是首选——小巧、快充且通过 MFi 认证，用户普遍好评做工质量。",
          },
          {
            query: "Fastest GaN charger under $50",
            queryZh: "50美元以内最快的 GaN 充电器",
            brandPosition: 1,
            snippet: "ChargeFast 65W leads this category. ChatGPT cited PCMag's Editor's Choice award and the safety certifications as key differentiators.",
            snippetZh: "ChargeFast 65W 领跑该品类。ChatGPT 引用了 PCMag 编辑选择奖及安全认证作为关键差异化因素。",
          },
        ],
        citationHealth: { expertReview: 65, community: 22, retail: 10, autoGenerated: 3, riskLevel: "healthy" },
      },
    ],
  },
};

// ── ProPower Global — Chinese Amazon FBA seller demo ──────────────────────────
DEMO_COMPANIES["propower-global"] = {
  slug: "propower-global",
  name: "ProPower Global",
  plan: "Growth Plan",
  planZh: "成长计划",
  planColor: "#22c55e",
  avgArrs: 54,
  brandsImproving: 1,
  nextScheduledRun: "2026-03-07T09:00:00Z",
  brands: [
    {
      name: "JumpStart Pro",
      category: "Car Jump Starters",
      categoryZh: "汽车应急启动电源",
      arrs: 41,
      weighted_sov: 19.3,
      sov_high: 23.7,
      trend: "up",
      trendDelta: "+5.1 pts this month",
      trendDeltaZh: "本月 +5.1 分",
      lastRun: "2026-02-28T08:00:00Z",
      competitors: ["NOCO", "TACKLIFE", "AVAPOW"],
      geo_score: 68,
      citation_rate: 44,
      sentiment: { positive: 72, neutral: 21, negative: 7 },
      by_model: { chatgpt: 21.4, claude: 18.7, perplexity: 19.3, gemini: 17.8 },
      sampleQueries: [
        {
          query: "Best car jump starter for cold weather 2026",
          queryZh: "2026年低温环境最佳汽车应急启动电源",
          brandPosition: 2,
          snippet: "JumpStart Pro 1500A peaks in cold-weather tests — AGM battery compatible and includes safety protection circuits. NOCO Boost GB40 ($99.95, Amazon Top 5 Car Electronics bestseller, ★4.6) edges it on brand recognition and AI citation volume.",
          snippetZh: "JumpStart Pro 1500A 在低温测试中表现出色——兼容 AGM 电池并内置安全保护电路。NOCO Boost GB40（$99.95，亚马逊汽车电子 Top 5 畅销品，★4.6）在品牌知名度和 AI 引用量上略胜一筹。",
        },
        {
          query: "Portable jump starter for SUV under $80",
          queryZh: "80美元以内适合 SUV 的便携式启动电源",
          brandPosition: null,
          snippet: "JumpStart Pro was not mentioned. NOCO Boost XL and TACKLIFE T8 Max were recommended. No independent third-party review site has benchmarked JumpStart Pro for SUV-class peak current.",
          snippetZh: "本次回答未提及 JumpStart Pro。NOCO Boost XL 和 TACKLIFE T8 Max 被推荐。目前没有第三方独立评测网站对 JumpStart Pro 的 SUV 级峰值电流进行过基准测试。",
        },
      ],
      citationHealth: { expertReview: 38, community: 28, retail: 25, autoGenerated: 9, riskLevel: "watch" },
    },
    {
      name: "DriveSafe Pro",
      category: "Dash Cameras",
      categoryZh: "行车记录仪",
      arrs: 78,
      weighted_sov: 5.2,
      sov_high: 4.1,
      trend: "down",
      trendDelta: "−5.3 pts this month",
      trendDeltaZh: "本月 −5.3 分",
      lastRun: "2026-02-28T08:00:00Z",
      competitors: ["Vantrue", "Garmin Dash Cam", "Nextbase", "BlackVue"],
      geo_score: 18,
      citation_rate: 9,
      sentiment: { positive: 28, neutral: 38, negative: 34 },
      by_model: { chatgpt: 5.1, claude: 4.8, perplexity: 5.6, gemini: 5.3 },
      sampleQueries: [
        {
          query: "Best 4K dash cam with parking mode 2026",
          queryZh: "2026年带停车监控的最佳4K行车记录仪",
          brandPosition: null,
          snippet: "DriveSafe Pro was not mentioned. Vantrue, Garmin, and Nextbase dominated. AI cited missing night-vision benchmarks and limited third-party reviews as gaps.",
          snippetZh: "本次回答未提及 DriveSafe Pro。Vantrue、Garmin 和 Nextbase 占据主导。AI 指出缺少夜视基准测试和第三方评测是主要短板。",
        },
        {
          query: "Reliable dash cam under $100 for rideshare drivers",
          queryZh: "100美元以内适合网约车司机的可靠行车记录仪",
          brandPosition: null,
          snippet: "DriveSafe Pro absent. Vantrue N2 Pro and Garmin 47 were top picks. No English-language review site has benchmarked DriveSafe Pro in this use case.",
          snippetZh: "DriveSafe Pro 缺席。Vantrue N2 Pro 和 Garmin 47 是首选。尚无英文评测网站对 DriveSafe Pro 进行此用途测评。",
        },
      ],
      citationHealth: { expertReview: 8, community: 15, retail: 31, autoGenerated: 46, riskLevel: "critical" },
    },
    {
      name: "FlexWear",
      category: "Outdoor Apparel",
      categoryZh: "户外运动服饰",
      arrs: 69,
      weighted_sov: 6.1,
      sov_high: 5.3,
      trend: "down",
      trendDelta: "−3.2 pts this month",
      trendDeltaZh: "本月 −3.2 分",
      lastRun: "2026-02-28T08:00:00Z",
      competitors: ["Columbia", "Under Armour", "Decathlon"],
      geo_score: 22,
      citation_rate: 11,
      sentiment: { positive: 41, neutral: 35, negative: 24 },
      by_model: { chatgpt: 6.8, claude: 5.4, perplexity: 6.1, gemini: 6.1 },
      sampleQueries: [
        {
          query: "Best budget outdoor jacket for hiking under $60",
          queryZh: "60美元以内最佳入门级徒步外套",
          brandPosition: null,
          snippet: "FlexWear was not mentioned. Columbia, Decathlon Forclaz, and Marmot dominated. AI cited insufficient independent review coverage and no waterproof certification data for FlexWear.",
          snippetZh: "本次回答未提及 FlexWear。Columbia、Decathlon Forclaz 和 Marmot 占据主导。AI 指出 FlexWear 缺乏独立评测和防水认证数据。",
        },
        {
          query: "Affordable gym workout clothes on Amazon 2026",
          queryZh: "2026年 Amazon 上实惠的健身运动服",
          brandPosition: null,
          snippet: "FlexWear absent. Under Armour, Nike, and generic Amazon brands with 5000+ reviews were recommended. AI flagged lack of material specification transparency.",
          snippetZh: "FlexWear 缺席。Under Armour、Nike 以及拥有5000+评论的 Amazon 品牌获推荐。AI 指出面料规格透明度不足。",
        },
      ],
      citationHealth: { expertReview: 11, community: 19, retail: 28, autoGenerated: 42, riskLevel: "critical" },
    },
  ],
};

export const DEMO_PLAYBOOKS: Record<string, ExecutionPlaybook> = {
  "techvision-pro": {
    contentBriefs: [
      {
        id: "cb-1",
        title: "VoltEdge vs Jackery 1000: Which Portable Power Station Wins in 2026?",
        titleZh: "VoltEdge vs Jackery 1000：2026年谁才是最强便携储能站？",
        targetKeyword: "best portable power station comparison",
        aiFormat: "Comparison listicle with spec table",
        aiFormatZh: "参数对比测评 + 规格数据表",
        status: "published",
        brand: "VoltEdge",
        dueDate: "2026-02-10",
      },
      {
        id: "cb-2",
        title: "How to Choose a Portable Power Station for Camping (2026 Buyer's Guide)",
        titleZh: "露营储能站怎么选？2026年完整购买指南",
        targetKeyword: "portable power station camping guide",
        aiFormat: "Long-form buyer's guide with FAQ",
        aiFormatZh: "长文购买指南 + 常见问题解答",
        status: "measuring",
        brand: "VoltEdge",
        dueDate: "2026-02-17",
      },
      {
        id: "cb-3",
        title: "VoltEdge 500: Best-in-Class for Weekend Overlanders",
        titleZh: "VoltEdge 500：越野露营首选储能站",
        targetKeyword: "best power station for overlanding",
        aiFormat: "Use-case narrative + specs",
        aiFormatZh: "使用场景叙述 + 规格参数",
        status: "draft",
        brand: "VoltEdge",
        dueDate: "2026-03-05",
      },
      {
        id: "cb-4",
        title: "Smart Lights That Actually Work: LumaPulse Honest Review",
        titleZh: "真正好用的智能灯：LumaPulse 真实使用评测",
        targetKeyword: "best smart home lights review",
        aiFormat: "Review article + setup tutorial",
        aiFormatZh: "使用评测 + 设置教程",
        status: "draft",
        brand: "LumaPulse",
        dueDate: "2026-03-08",
      },
      {
        id: "cb-5",
        title: "ChargeFast 140W GaN Charger: Why It's the Top Pick for MacBook Users",
        titleZh: "ChargeFast 140W GaN 充电器：MacBook 用户的最佳选择",
        targetKeyword: "best USB-C charger for MacBook",
        aiFormat: "Product spotlight + benchmark data",
        aiFormatZh: "产品深度评测 + 充电速度基准测试",
        status: "published",
        brand: "ChargeFast",
        dueDate: "2026-01-28",
      },
      {
        id: "cb-6",
        title: "GaN vs Silicon: Which USB-C Charger Technology Should You Buy?",
        titleZh: "GaN vs 硅基：USB-C 充电器哪种技术更值得买？",
        targetKeyword: "GaN charger vs silicon charger explained",
        aiFormat: "Educational explainer + recommendation",
        aiFormatZh: "技术科普 + 选购建议",
        status: "measuring",
        brand: "ChargeFast",
        dueDate: "2026-02-14",
      },
    ],

    citationTargets: [
      {
        id: "ct-1",
        publication: "Wirecutter / NYT",
        domainAuthority: 91,
        relevance: "high",
        status: "outreach sent",
        targetBrands: ["VoltEdge", "ChargeFast"],
        notes: "Editor covers power & charging. Sent press kit 2026-02-20.",
        notesZh: "负责电源与充电品类的编辑，已于 2026-02-20 发送产品资料包。",
      },
      {
        id: "ct-2",
        publication: "Tom's Guide",
        domainAuthority: 87,
        relevance: "high",
        status: "in negotiation",
        targetBrands: ["VoltEdge"],
        notes: "Review unit shipped. Follow up due 2026-03-01.",
        notesZh: "评测样品已寄出，计划于 2026-03-01 跟进。",
      },
      {
        id: "ct-3",
        publication: "PCMag",
        domainAuthority: 85,
        relevance: "high",
        status: "published",
        targetBrands: ["ChargeFast"],
        notes: "ChargeFast 140W named 'Editor's Choice' Feb 2026.",
        notesZh: "ChargeFast 140W 荣获 PCMag 2026年2月「编辑推荐」。",
      },
      {
        id: "ct-4",
        publication: "TechRadar",
        domainAuthority: 82,
        relevance: "high",
        status: "not started",
        targetBrands: ["LumaPulse"],
        notes: "Smart home roundup published quarterly. Next one in April.",
        notesZh: "智能家居季度横评，下一期在4月，现在布局正当时。",
      },
      {
        id: "ct-5",
        publication: "CNET",
        domainAuthority: 89,
        relevance: "high",
        status: "outreach sent",
        targetBrands: ["VoltEdge", "LumaPulse"],
        notes: "Reached out to two editors. No response yet.",
        notesZh: "已联系两位编辑，暂无回复，本周再次跟进。",
      },
      {
        id: "ct-6",
        publication: "Outdoor Gear Lab",
        domainAuthority: 73,
        relevance: "medium",
        status: "in negotiation",
        targetBrands: ["VoltEdge"],
        notes: "Perfect audience for camping/overlanding use case.",
        notesZh: "受众与露营/越野场景完美匹配，洽谈中。",
      },
      {
        id: "ct-7",
        publication: "Rtings.com",
        domainAuthority: 76,
        relevance: "medium",
        status: "not started",
        targetBrands: ["LumaPulse"],
        notes: "Adding smart lights category in Q2 2026.",
        notesZh: "计划于 2026 年 Q2 开设智能灯品类，提前接触。",
      },
      {
        id: "ct-8",
        publication: "AndroidCentral",
        domainAuthority: 80,
        relevance: "medium",
        status: "published",
        targetBrands: ["ChargeFast"],
        notes: "Featured in 'Best USB-C Chargers' roundup Jan 2026.",
        notesZh: "2026年1月入选「最佳 USB-C 充电器」年度横评。",
      },
    ],

    okrs: [
      {
        id: "okr-1",
        objective: "Dominate USB-C Charger category in AI recommendations",
        objectiveZh: "主导 USB-C 充电器品类的 AI 推荐排名",
        keyResult: "ChargeFast reaches 45% weighted SOV in USB-C Chargers",
        keyResultZh: "ChargeFast 加权 SOV 达到 45%（当前 31.8%）",
        current: 31.8,
        target: 45,
        startVal: 23.9,
        unit: "% SOV",
        lowerIsBetter: false,
        dueDate: "2026-03-31",
        status: "on track",
      },
      {
        id: "okr-2",
        objective: "Rescue LumaPulse AI visibility",
        objectiveZh: "拯救 LumaPulse 的 AI 可见度",
        keyResult: "LumaPulse ARRS score drops below 40 (from 61)",
        keyResultZh: "LumaPulse ARRS 分数从 61 降至 40 以下",
        current: 61,
        target: 40,
        startVal: 61,
        unit: "ARRS",
        lowerIsBetter: true,
        dueDate: "2026-03-31",
        status: "at risk",
      },
      {
        id: "okr-3",
        objective: "Establish VoltEdge as the go-to camping power brand",
        objectiveZh: "确立 VoltEdge 露营储能首选品牌地位",
        keyResult: "3 top-10 DA publications cite VoltEdge in camping/overlanding content",
        keyResultZh: "3 家 DA 前十媒体在露营/越野内容中引用 VoltEdge",
        current: 1,
        target: 3,
        startVal: 0,
        unit: "citations",
        lowerIsBetter: false,
        dueDate: "2026-03-31",
        status: "on track",
      },
    ],

    nextActions: [
      {
        id: "na-1",
        title: "Ship LumaPulse review unit to TechRadar",
        titleZh: "向 TechRadar 寄送 LumaPulse 评测样品",
        description: "TechRadar's smart home roundup is in April — get on their radar now.",
        descriptionZh: "TechRadar 智能家居横评在4月发布，现在寄样品刚好赶上编辑审阅周期。",
        priority: "urgent",
        assignee: "Marketing",
        dueDate: "2026-03-01",
        relatedBrand: "LumaPulse",
        done: false,
      },
      {
        id: "na-2",
        title: "Publish VoltEdge overlanding content brief (cb-3)",
        titleZh: "发布 VoltEdge 越野场景内容文章（cb-3）",
        description: "Brief is drafted — needs final review and publish to official blog.",
        descriptionZh: "文章已起草完毕，完成最终审核后发布到官方博客。",
        priority: "high",
        assignee: "Content",
        dueDate: "2026-03-05",
        relatedBrand: "VoltEdge",
        done: false,
      },
      {
        id: "na-3",
        title: "Follow up with Tom's Guide on VoltEdge review unit",
        titleZh: "跟进 Tom's Guide 的 VoltEdge 评测进展",
        description: "Unit shipped 2 weeks ago. Send a polite follow-up with updated spec sheet.",
        descriptionZh: "样品已寄出两周，发送一封礼貌的跟进邮件并附上最新规格说明书。",
        priority: "high",
        assignee: "PR",
        dueDate: "2026-03-01",
        relatedBrand: "VoltEdge",
        done: false,
      },
      {
        id: "na-4",
        title: "Add product FAQ schema to ChargeFast product pages",
        titleZh: "为 ChargeFast 产品页面添加 FAQ 结构化数据",
        description: "AI models frequently cite FAQ-structured pages. 5 key questions identified.",
        descriptionZh: "AI 模型优先引用 FAQ 结构化页面，已整理 5 个核心问题，完成上线。",
        priority: "high",
        assignee: "Engineering",
        dueDate: "2026-03-03",
        relatedBrand: "ChargeFast",
        done: true,
      },
      {
        id: "na-5",
        title: "Reach out to CNET smart home editor (LumaPulse)",
        titleZh: "联系 CNET 智能家居编辑（LumaPulse）",
        description: "Follow up on the initial outreach. Offer a 30-min product demo call.",
        descriptionZh: "跟进初次联系，邀请对方参加 30 分钟产品体验通话。",
        priority: "medium",
        assignee: "PR",
        dueDate: "2026-03-07",
        relatedBrand: "LumaPulse",
        done: false,
      },
    ],
  },

  "propower-global": {
    contentBriefs: [
      {
        id: "pp-cb-1",
        title: "JumpStart Pro 1500A Review: Best Cold-Weather Jump Starter of 2026?",
        titleZh: "JumpStart Pro 1500A 评测：2026年低温环境最佳汽车启动电源？",
        targetKeyword: "best car jump starter cold weather 2026",
        aiFormat: "Product review + cold-weather use-case benchmark",
        aiFormatZh: "产品评测 + 低温场景基准测试",
        status: "published",
        brand: "JumpStart Pro",
        dueDate: "2026-02-15",
      },
      {
        id: "pp-cb-2",
        title: "JumpStart Pro vs NOCO Boost Plus: Which Jump Starter Wins for SUVs?",
        titleZh: "JumpStart Pro vs NOCO Boost Plus：哪款更适合 SUV？",
        targetKeyword: "JumpStart Pro vs NOCO Boost jump starter comparison",
        aiFormat: "Head-to-head comparison with peak current data",
        aiFormatZh: "参数对比 + 峰值电流测试数据",
        status: "measuring",
        brand: "JumpStart Pro",
        dueDate: "2026-02-22",
      },
      {
        id: "pp-cb-3",
        title: "4K Dash Cam Showdown: DriveSafe Pro vs Vantrue N4 Pro",
        titleZh: "4K 行车记录仪对决：DriveSafe Pro vs Vantrue N4 Pro",
        targetKeyword: "best 4K dash cam comparison 2026",
        aiFormat: "Comparison review with night-vision benchmark data",
        aiFormatZh: "夜视基准测试对比评测",
        status: "draft",
        brand: "DriveSafe Pro",
        dueDate: "2026-03-10",
      },
      {
        id: "pp-cb-4",
        title: "DriveSafe Pro D3: Setup Guide for Rideshare Drivers",
        titleZh: "DriveSafe Pro D3 网约车司机安装使用指南",
        targetKeyword: "best dash cam for rideshare drivers",
        aiFormat: "How-to guide + driver use-case",
        aiFormatZh: "安装教程 + 驾驶场景案例",
        status: "draft",
        brand: "DriveSafe Pro",
        dueDate: "2026-03-14",
      },
      {
        id: "pp-cb-5",
        title: "FlexWear Hiking Jacket vs Columbia: Budget Outdoor Gear Compared",
        titleZh: "FlexWear 徒步外套 vs Columbia：平价户外装备横评",
        targetKeyword: "budget hiking jacket comparison 2026",
        aiFormat: "Comparison article + waterproof rating table",
        aiFormatZh: "对比文章 + 防水等级数据表",
        status: "draft",
        brand: "FlexWear",
        dueDate: "2026-03-12",
      },
    ],

    citationTargets: [
      {
        id: "pp-ct-1",
        publication: "Wirecutter / NYT",
        domainAuthority: 91,
        relevance: "high",
        status: "not started",
        targetBrands: ["JumpStart Pro"],
        notes: "Wirecutter's jump starter guide was last updated Nov 2025. Pitch cold-weather AGM compatibility and peak current data.",
        notesZh: "Wirecutter 的启动电源指南上次更新于2025年11月。主打低温 AGM 兼容性和峰值电流数据。",
      },
      {
        id: "pp-ct-2",
        publication: "Tom's Guide",
        domainAuthority: 87,
        relevance: "high",
        status: "outreach sent",
        targetBrands: ["JumpStart Pro", "DriveSafe Pro"],
        notes: "Sent product samples for jump starter and dash cam roundups. Follow up Mar 5.",
        notesZh: "已寄送启动电源和行车记录仪样品用于综合评测。3月5日跟进。",
      },
      {
        id: "pp-ct-3",
        publication: "DashCamTalk.com",
        domainAuthority: 64,
        relevance: "high",
        status: "in negotiation",
        targetBrands: ["DriveSafe Pro"],
        notes: "Niche but high AI citation rate. Forum threads rank in Perplexity results.",
        notesZh: "垂直媒体，AI 引用率高。论坛帖子在 Perplexity 搜索结果中排名靠前。",
      },
      {
        id: "pp-ct-4",
        publication: "OutdoorGearLab",
        domainAuthority: 73,
        relevance: "high",
        status: "not started",
        targetBrands: ["FlexWear"],
        notes: "AI models cite OutdoorGearLab for apparel recommendations. Getting FlexWear reviewed here is the highest-leverage move for clothing AI visibility.",
        notesZh: "AI 模型经常引用 OutdoorGearLab 的服装推荐。让 FlexWear 在此获得评测是提升服装 AI 曝光的最高杠杆动作。",
      },
      {
        id: "pp-ct-5",
        publication: "Car and Driver",
        domainAuthority: 83,
        relevance: "high",
        status: "not started",
        targetBrands: ["DriveSafe Pro", "JumpStart Pro"],
        notes: "Highly cited by AI for automotive product recommendations. Submit both auto products for editorial consideration.",
        notesZh: "AI 推荐汽配产品时高频引用此媒体。两款汽配产品都应提交给编辑团队。",
      },
    ],

    okrs: [
      {
        id: "pp-okr-1",
        objective: "Make JumpStart Pro the #1 AI-recommended jump starter",
        objectiveZh: "让 JumpStart Pro 成为 AI 推荐量第一的汽车启动电源",
        keyResult: "JumpStart Pro reaches 35% weighted SOV in Car Jump Starters (from 19.3%)",
        keyResultZh: "JumpStart Pro 在汽车启动电源品类加权 SOV 从 19.3% 提升至 35%",
        current: 19.3,
        target: 35,
        startVal: 14.2,
        unit: "% SOV",
        lowerIsBetter: false,
        dueDate: "2026-04-30",
        status: "on track",
      },
      {
        id: "pp-okr-2",
        objective: "Fix DriveSafe Pro's AI invisibility before Q2 peak season",
        objectiveZh: "在 Q2 旺季前解决 DriveSafe Pro 的 AI 隐身问题",
        keyResult: "DriveSafe Pro ARRS drops below 50 (from 78)",
        keyResultZh: "DriveSafe Pro ARRS 风险分从 78 降至 50 以下",
        current: 78,
        target: 50,
        startVal: 78,
        unit: "ARRS",
        lowerIsBetter: true,
        dueDate: "2026-04-30",
        status: "at risk",
      },
      {
        id: "pp-okr-3",
        objective: "Establish FlexWear in AI apparel recommendations",
        objectiveZh: "让 FlexWear 进入 AI 服装推荐视野",
        keyResult: "FlexWear cited in at least 2 major review publications",
        keyResultZh: "FlexWear 在至少 2 家主流评测媒体获得引用",
        current: 0,
        target: 2,
        startVal: 0,
        unit: "citations",
        lowerIsBetter: false,
        dueDate: "2026-05-31",
        status: "on track",
      },
    ],

    nextActions: [
      {
        id: "pp-na-1",
        title: "Submit DriveSafe Pro to DashCamTalk forum for community review",
        titleZh: "向 DashCamTalk 论坛提交 DriveSafe Pro 用于社区评测",
        description: "DashCamTalk threads appear in Perplexity results for dash cam queries. Community credibility = AI citations.",
        descriptionZh: "DashCamTalk 论坛帖子在 Perplexity 行车记录仪搜索中排名靠前。社区公信力 = AI 引用率提升。",
        priority: "urgent",
        assignee: "Marketing",
        dueDate: "2026-03-05",
        relatedBrand: "DriveSafe Pro",
        done: false,
      },
      {
        id: "pp-na-2",
        title: "Add English night-vision benchmark page for DriveSafe Pro D3",
        titleZh: "为 DriveSafe Pro D3 新增英文夜视基准测试页面",
        description: "No English benchmark data exists. AI models skip the brand because there's nothing to cite.",
        descriptionZh: "目前无任何英文基准测试数据。AI 模型因无可引用内容而跳过该品牌。",
        priority: "urgent",
        assignee: "Engineering",
        dueDate: "2026-03-07",
        relatedBrand: "DriveSafe Pro",
        done: false,
      },
      {
        id: "pp-na-3",
        title: "Publish JumpStart Pro vs NOCO comparison article",
        titleZh: "发布 JumpStart Pro vs NOCO 对比文章",
        description: "Content is in measuring phase — verify if Perplexity is citing it. If not, add peak current test data and FAQ schema.",
        descriptionZh: "内容处于观察阶段——确认 Perplexity 是否已引用。如未引用，补充峰值电流测试数据和 FAQ 结构化数据。",
        priority: "high",
        assignee: "Content",
        dueDate: "2026-03-06",
        relatedBrand: "JumpStart Pro",
        done: false,
      },
      {
        id: "pp-na-4",
        title: "Send FlexWear samples to OutdoorGearLab for apparel review",
        titleZh: "向 OutdoorGearLab 寄送 FlexWear 样品申请服装评测",
        description: "OutdoorGearLab is AI's #1 cited source for outdoor apparel. Getting reviewed here will unlock citations within 60 days.",
        descriptionZh: "OutdoorGearLab 是 AI 引用频次最高的户外服装媒体。在此获得评测后约60天内可显著提升 AI 引用率。",
        priority: "high",
        assignee: "Product",
        dueDate: "2026-03-10",
        relatedBrand: "FlexWear",
        done: false,
      },
    ],
  },
};
